services:
  test_deployment:
    build: .
    image: test_deployment:latest
    container_name: test_deployment
    volumes:
      - .:/workspace
    tty: true
    working_dir: /workspace
    command: ["bash"]
    # Uncomment the following line if you want to run a specific command on startup